import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LayoutDefault from './layoutDefault.js'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Clar Hope Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <div>
          <LayoutDefault/>
         </div>
    </div>
  )
}
